### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by emad555** [MingjunZhong/transferNILM#12]
When I run:

`python create_dataset.py --data_dir './' --appliance_name 'kettle' --aggregate_mean 522 --aggregate_std 814 --save_path './'`

I am getting the following error:
AttributeError: 'NoneType' object has no attribute 'group'

The dataset hierarchy:
![image](https://user-images.githubusercontent.com/60844745/224540996-1f7d383d-1ed0-4ef1-8b30-b2df593fe011.png)

**Comment by baldmaan** [comment]
Did you find a solution?

**Comment by emad555** [comment]
Yes, I changed the directory for the training dataset.
