### ISSUE TITLE
How to reproduce seq2seq based on this code?

### ISSUE THREAD

**Issue by Hessen525** [MingjunZhong/transferNILM#6]
@MingjunZhong 
Hi, Dr. Zhong.
I was trying to reproduce seq2seq, but i failed.
Train successfully, but test occur error. It is hard to fix that error for me. 
So, I wonder if you can share seq2seq code here if possible?

Thanks,
Appreciate!

**Comment by MingjunZhong** [comment]
@Hessen525  That's a great point, but I need time to re-code seq2seq soon. At the moment, this repository would help even it was old: https://github.com/MingjunZhong/NeuralNetNilm
What was the problems? For testing, you may have to mind the pre-processing for test data.

**Comment by Hessen525** [comment]
> @Hessen525 That's a great point, but I need time to re-code seq2seq soon. At the moment, this repository would help even it was old: https://github.com/MingjunZhong/NeuralNetNilm
> What was the problems? For testing, you may have to mind the pre-processing for test data.

Thanks for your reply, 
The error looks like that the shape of truth and prediction are different.
